#! /bin/bash

set -e

# limit = $1, defaults to 1000
limit=${1:-1000}

query ()
{
  psql -q -t -d "find_duplicates" -c "\pset format unaligned" -c "${1}"
}

for path in $(query "SELECT path FROM find_duplicates.files WHERE type='f' AND md5sum IS NULL LIMIT ${limit}")
do
  req=$(md5sum ${path} \
        | sed -re "s;^([^ ]+)[^/]+(.*)$;UPDATE find_duplicates.files SET md5sum='\1', updated_at=NOW() WHERE path='\2';")
  query "${req}"
done
