#! /bin/bash

set -e

psql -d "find_duplicates" -c "SELECT (SELECT COUNT(*) FROM find_duplicates.files WHERE type='f' AND md5sum IS NOT NULL) * 100 / (SELECT COUNT(*) FROM find_duplicates.files WHERE type='f') AS count_percent;"

psql -d find_duplicates <<-EOF
select count(*), type from find_duplicates.files group by type;
select count(*) AS files_without_hash from find_duplicates.files where md5sum is null and type='f';
select (select sum(size) from find_duplicates.files where md5sum is not null and type='f')/(select sum(size) from find_duplicates.files where type='f') * 100 AS size_percent;
select sum(size) / 1024 / 1024 / 1024 || ' Go' AS duplicate_size from find_duplicates.files where md5sum in (select md5sum from find_duplicates.files group by md5sum having count(0) > 1);
select count(*), updated_at from find_duplicates.files where type='d' group by updated_at order by updated_at limit 1;
EOF

# select md5sum, path from find_duplicates.files where md5sum in (select md5sum from find_duplicates.files group by md5sum having count(0) > 1) order by size DESC, md5sum;
