#! /bin/bash

set -e
set -o pipefail

path="$1"
max=${2:-1}

psql -q -t -d find_duplicates -c "UPDATE find_duplicates.files SET updated_at=NOW() WHERE path=\$\$${path}\$\$"

tmp=$(mktemp)

for t in d f
do
  find "${path}" -maxdepth ${max} -type ${t} \
    -exec stat -c ", (\$token\$%n\$token\$, \$\$${t}\$\$, %s)" '{}' + \
    >> ${tmp}
done

cat /home/armand/workspace/find_duplicates/template.sql ${tmp} /home/armand/workspace/find_duplicates/footer.sql \
  | psql -q -t -d "find_duplicates"
rm ${tmp}
